---
title: "Data Analysis"
toc: true
toc-location: left
---

This section covers various data analysis work I have done


# Project-portfolio
## CLV Prediction for Auto Insurance:
This notebook focuses on predicting Customer Lifetime Value (CLV) for auto insurance clients, utilizing various models to analyze data. It includes visual exploratory data analysis, inferential statistics, and multiple final model assessments to optimize prediction accuracy. 
[Python code](CLV.ipynb){target="_blank"}

## Simulation for Decision Making and Optimization - Operations:
This notebook details a complex decision-making scenario involving two potential product initiatives with varying cost structures and market potentials. Through simulation, it examines expected profits, cost distributions, pricing strategies, and the trade-offs a brand manager faces to achieve desired profit probabilities, enhancing decision-making in operations management.
[Python code](Simulation.ipynb){target="_blank"}

## Classification on Amazon SageMaker- Modelling:
The notebook describes the setup and execution of a machine learning pipeline using XGBoost and Amazon SageMaker, focusing on model training, hyperparameter tuning, and deployment for real-time inference, including detailed code for each stage.
[Python code](SageMaker- Modelling.ipynb){target="_blank"}

## Classification on Amazon SageMaker - Inference:
This notebook outlines the process of performing real-time inference using an XGBoost model deployed on Amazon SageMaker, detailing steps from exploratory data analysis, training with hyperparameter tuning, to evaluating and using the model for predicting salary categories.
[Python code](SageMaker- Inference.ipynb){target="_blank"}

## Google Review Analyze Text:
This extensive research project explores the use of various predictive modeling techniques to predict star ratings from the Google Local Dataset as part of a Recommender Systems course. The team employs regression techniques, latent factor models, classification, text-based classifiers, and sentiment analysis to determine the most effective approach. The study includes detailed exploratory data analysis, sentiment analysis of review texts, and the application of several predictive models, culminating in recommendations for similar analyses. The project emphasizes the predictive power of sentiment scores in star rating predictions, enhanced by additional data features and model complexities to refine accuracy and performance.
[Python code](Google_review_analysis.ipynb){target="_blank"}






